config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  root to: 'site#index'
  resources :entries, only: [:index, :create, :update], defaults: {format: 'json'}
  resources :messages, only: [:index]
  resources :main
  resources :matchings
  resources :settings, only:[:index, :show, :create, :update]
  resources :black_lists, except: [:show, :destroy]
  resources :white_lists, except: [:show]
  resources :cameras
  resources :parking_cameras, only:[:index, :update, :show, :destroy]
  resources :brands, only:[:show]

  put 'parking_cameras' => 'parking_cameras#update'
  post 'parking_cameras' => 'parking_cameras#create'
  post 'site/create_manual' => 'site#create_manual'
  get 'brands/all_brands' => 'brands#all_brands'
  post 'conf_manager' => 'settings#conf_manager'
  get 'get_conf_manager' => 'settings#get_conf_manager'
  post 'settings/path' => 'settings#path'
  get 'path_result' => 'settings#path_result'
  get 'drop_tables' => 'settings#drop_tables'
  post 'backup_usb' => 'settings#backup_usb'
  get 'reboot_system' => 'settings#reboot_system'

  get  'entries/search' => 'entries#search', as: 'entries_search'
  get  'entries/edited' => 'entries#edited', as: 'entries_edited'
  get  'black_lists/detected' => 'black_lists#detected', as: 'black_lists_detected'
  post 'black_lists/destroy'  => 'black_lists#destroy',  as: 'black_lists_destroy'
  get  'white_lists/detected' => 'white_lists#detected', as: 'white_lists_detected'
  post 'white_lists/search_b' => 'white_lists#search_b', as: 'white_lists_search_b'
  get  'white_lists/search'   => 'white_lists#search',   as: 'white_lists_search'
  post 'white_lists/destroy'  => 'white_lists#destroy',  as: 'white_lists_destroy'
  post 'white_lists/update'   => 'white_lists#update',   as: 'white_lists_update'
  post 'black_lists/search_w' => 'black_lists#search_w', as: 'black_lists_search_w'
  post 'settings/url_config'  => 'settings#url_config',  as: 'config_urls'
  post 'cameras/create' => 'cameras#create'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	attr_accessor :plate_segment, :creation_date, :full_image, :server_path

	#Default Scope
	default_scope{order(created_at: :desc)}
	
	#Callbacks
	after_validation :after_validation_callback
	before_create :after_validation_callback
	before_save :before_save_callback
	after_save :after_save_callback

	def entry_type_str
		if self.entry_type.nil?
			''
		else
			if self.entry_type == 1
				'Entrada'
			elsif self.entry_type == 2
				'Salida'
			end
		end
	end

	def date
		self.creation_date_at_device.strftime('%d/%m/%Y')
  	end

	def hours
		self.creation_date_at_device.strftime('%H:%M')
  end

  def time
  	if entry_type == 2
  		if !self.time_related.nil?
  			Time.diff(self.time_related, self.creation_date_at_device,'%h:%m:%s')[:diff]
			else
				'N-R'
			end
		else
			''
		end
	end

	def edited_str
		if self.edited.nil?
			''
		else
			if self.edited == true
				'Si'
			else
				'No'
			end
		end
	end

	def maximun_capacity
		parking_setting = ParkingSetting.first
		parking_setting.maximun_capacity
	end

	def available_capacity
		parking_setting = ParkingSetting.first
		parking_setting.available_capacity.nil? ? parking_setting.maximun_capacity : parking_setting.capacidad_disponible
	end

	def number_of_entries
		parking_setting = ParkingSetting.first
		parking_setting.number_of_entries.nil? ? 0 : parking_setting.number_of_entries
	end

	def need_to_edit
		self.plate_chars.include?('@')
	end

	def reason_black_list
		black_list = BlackList.where(plate: self.plate_chars)[0]
		
		if black_list.nil?
			''
		else
			black_list.motivo
		end
	end

	def reason_white_list
		white_list = WhiteList.where(plate: self.plate_chars)[0]
		
		if white_list.nil?
			''
		else
			white_list.motivo
		end 
	end

	private
	def before_save_callback
		if self.entry_type == 2
			entry_related = Entry.where(plate_chars: self.plate_chars, entry_type: 1, entry_related_id: nil)[0]

			if entry_related
				self.entry_related_id = entry_related.id
				self.tiempo_related = entry_related.creation_date_at_device
			end
		end

		self.edited = self.plate_chars.include?('@')
		nil
	end

	def after_save_callback
		if self.entry_type == 2
			entry_related = Entry.where(id: self.entry_related_id)[0]
			
			if entry_related
				entry_related.entry_related_id = self.id
				entry_related.save
			end
		end
	end

	def after_validation_callback
		if self.plate_segment_url.nil?
			now = Time.now
			plate_segment_image_name = "segment_"+plate_segment[:name]+'_'+now.strftime('%d%m%Y%H%M%S%L')+'.'+plate_segment[:ext]
			temp_plate_segment_url = Rails.root.join('public','photos',plate_segment_image_name)
			File.open(temp_plate_segment_url, 'wb') do|f|
			  f.write(Base64.decode64(plate_segment[:data]))
			end
			self.plate_segment_url = server_path+"/photos/"+plate_segment_image_name
		end

		if self.full_image_url.nil?
			now = Time.now
			full_image_name = "full_"+full_image[:name]+'_'+now.strftime('%d%m%Y%H%M%S%L')+'.'+full_image[:ext]
			temp_full_image_url = Rails.root.join('public','photos',full_image_name)
			File.open(temp_full_image_url, 'wb') do|f|
			  f.write(Base64.decode64(full_image[:data]))
			end		
			self.full_image_url = server_path+"/photos/"+full_image_name
		end

		if self.creation_date_at_device.nil?
			self.creation_date_at_device = creation_date
		end
	end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  #before_filter :authenticate, only: [:index]
  before_action :authenticate_user!, except: [:create]
  def index
    @entries = Entry.paginate(per_page: 100, page: params[:page])    
    respond_to do |format|
      format.html{}
      format.json{render json: @entries, status: :ok}
      format.xlsx {
        @entries = Entry.all
        render xlsx: "index", disposition: "attachment", filename: "Entradas.xlsx"
      }
    end
  end

  def create
  	entry = Entry.new(entry_params)

  	respond_to do |format|
  		temp = Entry.where(plate_chars: entry.plate_chars, entry_type: entry.entry_type, created_at: 90.seconds.ago..3.seconds.ago).count
      
      sw = false
      if temp < 3
        sw = true
      end

      if sw
        if entry.save          
          if entry.entry_type == 1 || entry.entry_type == 2
            if BlackList.where(plate: entry.plate_chars).count('id') > 0
              WebsocketRails[:real_broadcast].trigger('black_list', EntrySerializer.new(entry))            
            elsif WhiteList.where(plate: entry.plate_chars).count('id') > 0
              WebsocketRails[:real_broadcast].trigger('white_list', EntrySerializer.new(entry))
              if entry.entry_type == 1
		            %x['/home/odroid/Documents/199']
              end
              if entry.entry_type == 2
                %x['/home/odroid/Documents/200']
              end
            else
              WebsocketRails[:real_broadcast].trigger('other_entries', EntrySerializer.new(entry))
	            if entry.entry_type == 2
                %x['/home/odroid/Documents/200']
              end
            end            
          end #end entry ||

          format.json{render json: entry, status: :ok}  
        else
          format.json{render json: entry.errors.to_json, status: :unprocessable_entity}
        end
      else
        format.json{render json: "REPEATED".to_json, status: :ok}
      end
    end #end repond
  end

  def update
    @entry = Entry.find(params[:id])
    @entry.edited = true

    respond_to do |format|
      format.json{
        if @entry.update_attributes(entry_params_update)
          render json: @entry, status: :ok
        else
          render json: @entry.errors.to_json, status: 422
        end
      }
    end
  end

  def search
    @plate_chars = params[:plate_chars]
    @initial_date = params[:initial_date]
    @final_date = params[:final_date]

    if @initial_date != ""
      initial_date_format = @initial_date.split('/')
      initial_date = Date.new(initial_date_format[2].to_i, initial_date_format[1].to_i, initial_date_format[0].to_i)
      initial_date = initial_date.beginning_of_day
    end

    if @final_date != ""
      final_date_format = @final_date.split('/')
      final_date = Date.new(final_date_format[2].to_i, final_date_format[1].to_i, final_date_format[0].to_i)
      final_date = final_date.end_of_day
    end

    if @plate_chars != "" && @initial_date == "" && @final_date == ""
      @entries = Entry.where("plate_chars = ?", @plate_chars).paginate(per_page: 100, page: params[:page])
      @entries_xls = Entry.where("plate_chars = ?", @plate_chars)
    end

    if @plate_chars != "" && @initial_date != "" && @final_date == ""
      @entries = Entry.where("plate_chars = ? AND creation_date_at_device >= ?", @plate_chars, initial_date).paginate(per_page: 100, page: params[:page])
      @entries_xls = Entry.where("plate_chars = ? AND creation_date_at_device >= ?", @plate_chars, initial_date)
    end

    if @plate_chars != "" && @initial_date != "" && @final_date != ""
        @entries = Entry.where("plate_chars = ? AND creation_date_at_device >= ? AND creation_date_at_device <= ?", @plate_chars, initial_date, final_date).paginate(per_page: 100, page: params[:page])
        @entries_xls = Entry.where("plate_chars = ? AND creation_date_at_device >= ? AND creation_date_at_device <= ?", @plate_chars, initial_date, final_date)
    end

    if @plate_chars == "" && @initial_date != "" && @final_date != ""
      @entries = Entry.where("creation_date_at_device >= ? AND creation_date_at_device <= ?", initial_date, final_date).paginate(per_page: 100, page: params[:page])
      @entries_xls = Entry.where("creation_date_at_device >= ? AND creation_date_at_device <= ?", initial_date, final_date)
    end

    if @plate_chars == "" && @initial_date == "" && @final_date != ""
        @entries = Entry.where("creation_date_at_device <= ?", final_date).paginate(per_page: 100, page: params[:page])
        @entries_xls = Entry.where("creation_date_at_device <= ?", final_date)
    end

    if @plate_chars != "" && @initial_date == "" && @final_date != ""
        @entries = Entry.where("plate_chars = ? AND creation_date_at_device <= ?", @plate_chars, final_date).paginate(per_page: 100, page: params[:page])
        @entries_xls = Entry.where("plate_chars = ? AND creation_date_at_device <= ?", @plate_chars, final_date)
    end

    if @plate_chars == "" && @initial_date != "" && @final_date == ""
        @entries = Entry.where("creation_date_at_device >= ?", initial_date).paginate(per_page: 100, page: params[:page])
        @entries_xls = Entry.where("creation_date_at_device >= ?", initial_date)
    end

    if @plate_chars == "" && @initial_date == "" && @final_date == "" 
      @entries = Entry.all.paginate(per_page: 100, page: params[:page])
      @entries_xls = Entry.all
    end
    respond_to do |format|
      format.html{}
      format.xlsx {
        render xlsx: "search", disposition: "attachment", filename: "busqueda.xlsx"
      }
    end
  end

  def edited
    @entries = Entry.where(edited: true).paginate(per_page: 100, page: params[:page])
  end

  private

  def entry_params
    temp = params.permit(:device_id, :plate_chars, :plate_segment, :creation_date, :entry_type, full_image: [:data,:ext,:name], plate_segment: [:data,:ext,:name])
    r = request.url.split('/')
    temp[:server_path] = r.size > 4 ? r[2]+'/'+r[3] : r[2] 
    temp
  end

  def entry_params_update
    params.require(:entry).permit(:plate_chars)
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "ebenezer" && password == "123456"
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/edited.html.erb
<%content_for :javascript do%>
  <%= stylesheet_link_tag 'jquery-ui.min', :media => 'all' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag 'additional-methods' %>
  <%=javascript_include_tag 'entries'%>
<%end%>
<div class="row">
	<h2>Lista de Entradas y Salidas Corregidas</h2>
	<table class="tablelist responsive">
	  <thead>
	    <tr>
	      <th class="text-center">Placa</th>
	      <th class="text-center">Entrada/Salida</th>
	      <th class="text-center">Fecha</th>
	      <th class="text-center">Hora</th>
	      <th class="text-center">Segmento</th>
	      <th class="text-center">Tiempo</th>
	      <th class="text-center">Corregida</th>
	    </tr>
	  </thead>
	  <tbody>
	    <%@entries.each do |entry|%>
	    	<tr>
		      <td><%=entry.plate_chars%></td>
		      <td><%=entry.entry_type_str%></td>		      
		      <td><%=entry.date%></td>
		      <td><%=entry.hours%></td>
		      <td><ul class="clearing-thumbs" data-clearing><li><a href="http://<%=entry.full_image_url%>"><%=image_tag 'http://'+entry.plate_segment_url, class: "imgsegment"%></a></li></ul></td>
		      <td><%=entry.time%></td>
		      <td><%=entry.edited_str%></td>
		    </tr>	
	    <%end%>
	  </tbody>
	</table>
	<%= will_paginate @entries, previous_label: "Anterior", next_label: "Siguiente" %>
</div>

app/views/entries/index.html.erb
<%content_for :javascript do%>
  <%= stylesheet_link_tag 'jquery-ui.min', :media => 'all' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%=javascript_include_tag 'entries'%>
<%end%>
<div class="row">
	<h2>Lista de Entradas y Salidas</h2>
	<%=form_tag entries_search_path, method: :get do |f|%>
    <div class="row borderbsearch">
  		<div class="small-12 large-3 columns">
        <div class="large-12 columns">
  			 <input type="text" id="datepicker_intitial" placeholder="Fecha Inicial" name="fecha_inicial">
        </div>
  		</div>
  		<div class="small-12 large-3 columns">
        <div class="large-12 columns">
  			 <input type="text" id="datepicker_final" placeholder="Fecha Final" name="fecha_final">
        </div>
  		</div>
    	<div class="small-12 large-3 columns">
    		<div class="large-12 columns">
  		    <input type="text" placeholder="Placa" name="plate_chars" id="entry_plate_chars"/>
  		  </div>
    	</div>
      <div class="small-12 large-3 columns">
        <div class="large-12 columns text-center">
          <button type="submit" class="button">
            Buscar <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
  	</div>
  <%end%>
	<%=link_to "Descargar <i class='fa fa-download'></i>".html_safe, entries_path(format: :xlsx), class: 'button'%>
  <table class="tablelist responsive">
	  <thead>
	    <tr>
	      <th class="text-center">Placa</th>
	      <th class="text-center">Entrada/Salida</th>
	      <th class="text-center">Fecha</th>
	      <th class="text-center">Hora</th>
	      <th class="text-center">Segmento</th>
	      <th class="text-center">Tiempo</th>
	      <th class="text-center">Corregida</th>
	    </tr>
	  </thead>
	  <tbody>
	    <%@entries.each do |entry|%>
	    	<tr>
		      <td><%=entry.plate_chars%></td>
		      <td><%=entry.entry_type_str%></td>		      
		      <td><%=entry.date%></td>
		      <td><%=entry.hours%></td>
		      <td><ul class="clearing-thumbs" data-clearing><li>
			<% if entry.plate_segment_url == "" %>
		      	<a href="http://<%=entry.full_image_url%>" class="button small">Registro Manual</a>
		      	<% else %>		      	
		      	<a href="http://<%=entry.full_image_url%>"><%=image_tag 'http://'+entry.plate_segment_url, class: "imgsegment"%>
			<% end %>
			</li></ul></td>
		      <td><%=entry.time%></td>
		      <td><%=entry.edited_str%></td>
		    </tr>	
	    <%end%>
	  </tbody>
	</table>
	<%= will_paginate @entries, previous_label: "Anterior", next_label: "Siguiente" %>
</div>

app/views/entries/search.html.erb
<%content_for :javascript do%>
  <%= stylesheet_link_tag 'jquery-ui.min', :media => 'all' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag 'additional-methods' %>
  <%=javascript_include_tag 'entries'%>
<%end%>
<div class="row">
	<h2>Lista de Entradas y Salidas</h2>
	<%=form_tag entries_search_path, method: :get do |f|%>
    <div class="row borderbsearch">
  		<div class="small-12 large-3 columns">
        <div class="large-12 columns">
  			 <input type="text" id="datepicker_inicial" placeholder="Fecha Inicial" name="initial_date" value="<%=@initial_date.nil? ? '' : @initial_date%>">
        </div>
  		</div>
  		<div class="small-12 large-3 columns">
        <div class="large-12 columns">
  			 <input type="text" id="datepicker_final" placeholder="Fecha Final" name="final_date" value="<%=@final_date.nil? ? '' : @final_date%>">
        </div>
  		</div>
    	<div class="small-12 large-3 columns">
    		<div class="large-12 columns">
  		    <input type="text" placeholder="Placa" name="plate_chars" value="<%=@plate_chars.nil? ? '' : @plate_chars%>" id="entry_plate_chars"/>
  		  </div>
    	</div>
      <div class="small-12 large-3 columns">
        <div class="large-12 columns text-center">
          <button type="submit" class="button">
            Buscar <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
  	</div>
  	<%end%>
	   <%=link_to "Descargar <i class='fa fa-download'></i>".html_safe, entries_search_path(format: :xlsx, initial_date: params[:initial_date], final_date: params[:final_date], plate_chars: params[:plate_chars]), class: 'button'%>
  	<table class="tablelist responsive">
	  <thead>
	    <tr>
	      <th class="text-center">Placa</th>
	      <th class="text-center">Entrada/Salida</th>
	      <th class="text-center">Fecha</th>
	      <th class="text-center">Hora</th>
	      <th class="text-center">Segmento</th>
	      <th class="text-center">Tiempo</th>
	      <th class="text-center">Corregida</th>
	    </tr>
	  </thead>
	  <tbody>
	    <%@entries.each do |entry|%>
	    	<tr>
		      <td><%=entry.plate_chars%></td>
		      <td><%=entry.entry_type_str%></td>		      
		      <td><%=entry.date%></td>
		      <td><%=entry.hours%></td>
		      <td><ul class="clearing-thumbs" data-clearing><li><a href="http://<%=entry.full_image_url%>"><%=image_tag 'http://'+entry.plate_segment_url, class: "imgsegment"%></a></li></ul></td>
		      <td><%=entry.time%></td>
		      <td><%=entry.edited_str%></td>
		    </tr>	
	    <%end%>
	  </tbody>
	</table>
	<%= will_paginate @entries, previous_label: "Anterior", next_label: "Siguiente" %>
</div>