config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  root to: 'site#index'
  resources :entries, only: [:index, :create, :update], defaults: {format: 'json'}
  resources :messages, only: [:index]
  resources :main
  resources :matchings
  resources :settings, only:[:index, :show, :create, :update]
  resources :black_lists, except: [:show, :destroy]
  resources :white_lists, except: [:show]
  resources :cameras
  resources :parking_cameras, only:[:index, :update, :show, :destroy]
  resources :brands, only:[:show]

  put 'parking_cameras' => 'parking_cameras#update'
  post 'parking_cameras' => 'parking_cameras#create'
  post 'site/create_manual' => 'site#create_manual'
  get 'brands/all_brands' => 'brands#all_brands'
  post 'conf_manager' => 'settings#conf_manager'
  get 'get_conf_manager' => 'settings#get_conf_manager'
  post 'settings/path' => 'settings#path'
  get 'path_result' => 'settings#path_result'
  get 'drop_tables' => 'settings#drop_tables'
  post 'backup_usb' => 'settings#backup_usb'
  get 'reboot_system' => 'settings#reboot_system'

  get  'entries/search' => 'entries#search', as: 'entries_search'
  get  'entries/edited' => 'entries#edited', as: 'entries_edited'
  get  'black_lists/detected' => 'black_lists#detected', as: 'black_lists_detected'
  post 'black_lists/destroy'  => 'black_lists#destroy',  as: 'black_lists_destroy'
  get  'white_lists/detected' => 'white_lists#detected', as: 'white_lists_detected'
  post 'white_lists/search_b' => 'white_lists#search_b', as: 'white_lists_search_b'
  get  'white_lists/search'   => 'white_lists#search',   as: 'white_lists_search'
  post 'white_lists/destroy'  => 'white_lists#destroy',  as: 'white_lists_destroy'
  post 'white_lists/update'   => 'white_lists#update',   as: 'white_lists_update'
  post 'black_lists/search_w' => 'black_lists#search_w', as: 'black_lists_search_w'
  post 'settings/url_config'  => 'settings#url_config',  as: 'config_urls'
  post 'cameras/create' => 'cameras#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registable, :trackable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
  	super and self.is_active?	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_admin, :except => [:edit]
  
  def index
    @users = User.order("role").order("full_name")
  end

  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Nuevo usuario creado."
      redirect_to users_path
    else
      if @user.errors.keys == [:email]
        flash[:notice] = "Correo electrónico está en uso."  
      end      
      render :new
    end
  end

  def edit
    if current_user.id == params[:id].to_i
      @user = User.find(params[:id])
    else
      if current_user.role == "admin"
        @user = User.find(params[:id])
      else 
        redirect_to root_path
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end
    if @user.update_attributes(user_params)
      flash[:success] = "Usuario editado satisfactoriamente."
      redirect_to "/admin/users/#{@user.id}/edit"
    else
      if @user.errors.keys == [:email]
        flash[:notice] = "Correo electrónico está en uso."  
      end
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if params[:opt] == "1"
      @user.is_active = false
      if @user.save
        flash[:success] = "Usuario bloqueado satisfactoriamente."
      else
        flash[:notice] = "No se pudo bloquear este usuario."  
      end
    else
      @user.is_active = true
      if @user.save
        flash[:success] = "Usuario desbloqueado satisfactoriamente."
      else
        flash[:notice] = "No se pudo desbloquear este usuario."  
      end
    end
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:role, :full_name, :colombian_id, :email, :password, :password_confirmation, :created_by)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%content_for :javascript do%>
	<%=javascript_include_tag "users"%>
<%end%>

<div class="row">
	<h2>Edición de usuario</h2>
	<% flash.each do |key, value| %>
		<% if key == "success" %>
			<div data-alert class="alert-box success radius">
	  			<%= value %> <a href="/admin/users/">Volver</a>
	  			<a href="#" class="close">&times;</a>
			</div>
		<% end %>
		<% if key == "notice" %>
			<div data-alert class="alert-box alert radius">
	  			<%= value %>
	  			<a href="#" class="close">&times;</a>
			</div>
		<% end %>
    <% end %>
    
	<div id="errores"></div>
	<%= form_for(@user, html: {method: :put}) do |f| %>

		<% if current_user.role == "admin" %>	
		<p><label for="user_role"><strong>Tipo de usuario: </strong></label></p>
		<p>
			<select name="user[role]" id="user_role">
				<option value="admin" <% if @user.role == "admin"%> selected <% end %> >Administrador</option>
				<option value="user" <% if @user.role == "user"%> selected <% end %>>Usuario</option>
			</select>
		</p>
		<% end %>

		<p><label for="user_full_name"><strong>Nombres y Apellidos: </strong></label></p>
		<p><%= text_field_tag :user_full_name, nil, name: "user[full_name]", class: "input_edit_form", value: @user.full_name %></p>

		<p><label for="user_colombian_id"><strong>Cédula: </strong></label></p>
		<p><%= text_field_tag :user_colombian_id, nil, name: "user[colombian_id]", class: "input_edit_form", value: @user.colombian_id %></p>

		<p><label for="user_email"><strong>E-mail: </strong></label></p>
		<p><%= email_field_tag :user_email, nil, name: "user[email]", class: "input_edit_form", value: @user.email %></p>

		<p><label for="user_password"><strong>Contraseña: </strong></label></p>
		<p><%= password_field_tag :user_password, nil, autocomplete: "off", name: "user[password]" %></p>

		<p><label for="user_password_confirmation"><strong>Confirmación de contraseña: </strong></label></p>
		<p><%= password_field_tag :user_password_confirmation, nil, autocomplete: "off", name: "user[password_confirmation]" %></p>

		<p><%= f.submit "Guardar", class: "button" %></p>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="row">
	<h1>Usuarios del sistema</h1>

	<% flash.each do |key, value| %>
		<div data-alert class="alert-box success radius">
  			<%= value %>
  			<a href="#" class="close">&times;</a>
		</div>
    	
    <% end %>

	<ul class="button-group">
	  	<li><a href="<%= new_user_path %>" class="button"><strong>Nuevo</strong></a></li>
	</ul>

	<table class="tablelist responsive">
		<thead>
			<tr>
				<th class="text-center"><strong>No.</strong></th>
				<th class="text-center"><strong>Tipo de usuario</strong></th>
				<th class="text-center"><strong>Nombres y Apellidos</strong></th>
				<th class="text-center"><strong>E-mail</strong></th>
				<th class="text-center" width="260"><strong>Acciones</strong></th>
			</tr>
		</thead>
		<tbody>
			<% num = 1 %>
			<% @users.each do |user| %>
				<tr>
					<td class="text-center"><%= num %></td>
					<td class="text-center">
					<% if user.role == "admin" %>
						Administrador
					<% else %>
						Usuario
					<% end %>
					</td>
					<td class="text-center"><%= user.full_name %></td>
					<td class="text-center"><%= user.email %></td>
					<td class="text-center">
					<a href="/admin/users/<%= user.id %>/edit" class="button small"><strong>Editar</strong></a>
					<% if user.is_active? %><a href="/admin/users/<%= user.id %>?opt=1" data-method="delete" rel="nofollow" data-confirm="¿Está seguro de bloquear este usuario?" class="button small alert"><strong>Bloquear</strong></a>
					<% else %>
					<a href="/admin/users/<%= user.id %>?opt=2" data-method="delete" rel="nofollow" class="button small success"><strong>Desbloquear</strong></a>
					<% end %>
					</td>
				</tr>
				<% num = num + 1 %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/new.html.erb
<%content_for :javascript do%>
	<%=javascript_include_tag "users"%>
<%end%>
<br>
<div class="row">
	<% flash.each do |key, value| %>
		<% if key == "success" %>
			<div data-alert class="alert-box success radius">
	  			<%= value %> <a href="/admin/users/">Volver</a>
	  			<a href="#" class="close">&times;</a>
			</div>
		<% end %>
		<% if key == "notice" %>
			<div data-alert class="alert-box alert radius">
	  			<%= value %>
	  			<a href="#" class="close">&times;</a>
			</div>
		<% end %>
    <% end %>

	<h2>Nuevo usuario</h2>
	<div id="errores"></div>
	<%= form_for(@user) do |f| %>

		<p><label for="user_role"><strong>Tipo de usuario: </strong></label></p>
		<p>
			<select name="user[role]" id="user_role">
				<option value="admin">Administrador</option>
				<option value="user">Usuario</option>
			</select>
		</p>

		<p><label for="user_full_name"><strong>Nombres y apellidos: </strong></label></p>
		<p><%= text_field_tag :user_full_name, nil, name: "user[full_name]", class: "input_new_form", value: @user.full_name %></p>

		<p><label for="user_colombian_id"><strong>Cédula: </strong></label></p>
		<p><%= text_field_tag :user_colombian_id, nil, name: "user[colombian_id]", class: "input_new_form", value: @user.colombian_id %></p>

		<p><label for="user_email"><strong>E-mail: </strong></label></p>
		<p><%= email_field_tag :user_email, nil, name: "user[email]", class: "input_new_form", value: @user.email %></p>

		<p><label for="user_password"><strong>Contraseña: </strong></label></p>
		<p><%= password_field_tag :user_password, nil, name: "user[password]", autocomplete: "off", class: "input_new_form" %></p>

		<p><label for="user_password_confirmation"><strong>Confirmación de contraseña: </strong></label></p>
		<p><%= password_field_tag :user_password_confirmation, nil, name: "user[password_confirmation]", autocomplete: "off", class: "input_new_form" %></p>

		<input type="hidden" name="user[created_by]" value="<%= current_user.id %>">

		<p><%= f.submit "Guardar", class: "button" %></p>
	<% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>