config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  root to: 'site#index'
  resources :entries, only: [:index, :create, :update], defaults: {format: 'json'}
  resources :messages, only: [:index]
  resources :main
  resources :matchings
  resources :settings, only:[:index, :show, :create, :update]
  resources :black_lists, except: [:show, :destroy]
  resources :white_lists, except: [:show]
  resources :cameras
  resources :parking_cameras, only:[:index, :update, :show, :destroy]
  resources :brands, only:[:show]

  put 'parking_cameras' => 'parking_cameras#update'
  post 'parking_cameras' => 'parking_cameras#create'
  post 'site/create_manual' => 'site#create_manual'
  get 'brands/all_brands' => 'brands#all_brands'
  post 'conf_manager' => 'settings#conf_manager'
  get 'get_conf_manager' => 'settings#get_conf_manager'
  post 'settings/path' => 'settings#path'
  get 'path_result' => 'settings#path_result'
  get 'drop_tables' => 'settings#drop_tables'
  post 'backup_usb' => 'settings#backup_usb'
  get 'reboot_system' => 'settings#reboot_system'

  get  'entries/search' => 'entries#search', as: 'entries_search'
  get  'entries/edited' => 'entries#edited', as: 'entries_edited'
  get  'black_lists/detected' => 'black_lists#detected', as: 'black_lists_detected'
  post 'black_lists/destroy'  => 'black_lists#destroy',  as: 'black_lists_destroy'
  get  'white_lists/detected' => 'white_lists#detected', as: 'white_lists_detected'
  post 'white_lists/search_b' => 'white_lists#search_b', as: 'white_lists_search_b'
  get  'white_lists/search'   => 'white_lists#search',   as: 'white_lists_search'
  post 'white_lists/destroy'  => 'white_lists#destroy',  as: 'white_lists_destroy'
  post 'white_lists/update'   => 'white_lists#update',   as: 'white_lists_update'
  post 'black_lists/search_w' => 'black_lists#search_w', as: 'black_lists_search_w'
  post 'settings/url_config'  => 'settings#url_config',  as: 'config_urls'
  post 'cameras/create' => 'cameras#create'

end

app/models/black_list.rb
class BlackList < ActiveRecord::Base
	#Default_Scope
	default_scope{order('plate asc')}
	
	#Validations
	validates :plate, presence: true

	#Callbacks
	before_save :before_save_callback

	private
	def before_save_callback
		self.plate = plate.upcase
	end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :ref_cameras
	validates :brand, uniqueness: true
end

app/models/conf_manager.rb
class ConfManager < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	attr_accessor :plate_segment, :creation_date, :full_image, :server_path

	#Default Scope
	default_scope{order(created_at: :desc)}
	
	#Callbacks
	after_validation :after_validation_callback
	before_create :after_validation_callback
	before_save :before_save_callback
	after_save :after_save_callback

	def entry_type_str
		if self.entry_type.nil?
			''
		else
			if self.entry_type == 1
				'Entrada'
			elsif self.entry_type == 2
				'Salida'
			end
		end
	end

	def date
		self.creation_date_at_device.strftime('%d/%m/%Y')
  	end

	def hours
		self.creation_date_at_device.strftime('%H:%M')
  end

  def time
  	if entry_type == 2
  		if !self.time_related.nil?
  			Time.diff(self.time_related, self.creation_date_at_device,'%h:%m:%s')[:diff]
			else
				'N-R'
			end
		else
			''
		end
	end

	def edited_str
		if self.edited.nil?
			''
		else
			if self.edited == true
				'Si'
			else
				'No'
			end
		end
	end

	def maximun_capacity
		parking_setting = ParkingSetting.first
		parking_setting.maximun_capacity
	end

	def available_capacity
		parking_setting = ParkingSetting.first
		parking_setting.available_capacity.nil? ? parking_setting.maximun_capacity : parking_setting.capacidad_disponible
	end

	def number_of_entries
		parking_setting = ParkingSetting.first
		parking_setting.number_of_entries.nil? ? 0 : parking_setting.number_of_entries
	end

	def need_to_edit
		self.plate_chars.include?('@')
	end

	def reason_black_list
		black_list = BlackList.where(plate: self.plate_chars)[0]
		
		if black_list.nil?
			''
		else
			black_list.motivo
		end
	end

	def reason_white_list
		white_list = WhiteList.where(plate: self.plate_chars)[0]
		
		if white_list.nil?
			''
		else
			white_list.motivo
		end 
	end

	private
	def before_save_callback
		if self.entry_type == 2
			entry_related = Entry.where(plate_chars: self.plate_chars, entry_type: 1, entry_related_id: nil)[0]

			if entry_related
				self.entry_related_id = entry_related.id
				self.tiempo_related = entry_related.creation_date_at_device
			end
		end

		self.edited = self.plate_chars.include?('@')
		nil
	end

	def after_save_callback
		if self.entry_type == 2
			entry_related = Entry.where(id: self.entry_related_id)[0]
			
			if entry_related
				entry_related.entry_related_id = self.id
				entry_related.save
			end
		end
	end

	def after_validation_callback
		if self.plate_segment_url.nil?
			now = Time.now
			plate_segment_image_name = "segment_"+plate_segment[:name]+'_'+now.strftime('%d%m%Y%H%M%S%L')+'.'+plate_segment[:ext]
			temp_plate_segment_url = Rails.root.join('public','photos',plate_segment_image_name)
			File.open(temp_plate_segment_url, 'wb') do|f|
			  f.write(Base64.decode64(plate_segment[:data]))
			end
			self.plate_segment_url = server_path+"/photos/"+plate_segment_image_name
		end

		if self.full_image_url.nil?
			now = Time.now
			full_image_name = "full_"+full_image[:name]+'_'+now.strftime('%d%m%Y%H%M%S%L')+'.'+full_image[:ext]
			temp_full_image_url = Rails.root.join('public','photos',full_image_name)
			File.open(temp_full_image_url, 'wb') do|f|
			  f.write(Base64.decode64(full_image[:data]))
			end		
			self.full_image_url = server_path+"/photos/"+full_image_name
		end

		if self.creation_date_at_device.nil?
			self.creation_date_at_device = creation_date
		end
	end
end

app/models/parking_camera.rb
class ParkingCamera < ActiveRecord::Base
	belongs_to :ref_camera
end

app/models/parking_setting.rb
class ParkingSetting < ActiveRecord::Base
	#Validations
	validates :name, presence: true
	validates :number_of_entries, :maximum_capacity, numericality: true

	#Callbacks
	before_save :before_save_callback

	private
	def before_save_callback
		self.available_capacity = self.maximum_capacity - self.number_of_entries
	end
end

app/models/ref_camera.rb
class RefCamera < ActiveRecord::Base
	belongs_to :brand

	validates :reference, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registable, :trackable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
  	super and self.is_active?	
  end
end

app/models/white_list.rb
class WhiteList < ActiveRecord::Base
	#Default_Scope
	default_scope{order('plate asc')}
	
	#Validations
	validates :plate, presence: true

	#Callbacks
	before_save :before_save_callback

	private
	def before_save_callback
		self.plate = plate.upcase
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/black_list_helper.rb
module BlackListHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/matchings_helper.rb
module MatchingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/setting_helper.rb
module SettingHelper

	def network_conf(ip,mask,gateway,dns_one,dns_two)

	    system("sudo rm /etc/network/interfaces")
	    archivo = File.open("/home/odroid/interfaces", "w+")
	    archivo.puts "auto lo"
	    archivo.puts "iface lo inet loopback"
	    archivo.puts "###------->"
	    archivo.puts "auto eth0"
	    archivo.puts "iface eth0 inet static"
	    archivo.puts "address #{ip}"
	    archivo.puts "netmask #{mask}"
	    archivo.puts "gateway #{gateway}"
	    archivo.puts "dns-nameservers #{dns_one}"
	    archivo.puts "dns-nameservers #{dns_two}"
	    archivo.close()
	    system("sudo mv /home/odroid/interfaces /etc/network/")	
	end

	def find_device
		output = `lsblk`
		archivo = File.open("lsblk.txt","w+")
		archivo.puts output
		archivo.close()

		archivo = File.open("lsblk.txt","r")
		$ARRAY = archivo.readlines
		archivo.close()
		return $ARRAY
	end

end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Ebenezer Techs" %></title>
    
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <br>
    <div class="row">      
      <div class="right">      
        <% if user_signed_in? %>
          Estás logeado como <a href="/admin/users/<%= current_user.id %>/edit"> <%= current_user.full_name %></a>. 
          <%= link_to('Salir', destroy_user_session_path, :method=>'delete') %>  
        <%end%>
      </div>
    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="<%= root_path %>"><%= image_tag "ebenezer.png", class: "logoeb"%></a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li <% if params[:controller] == 'site' %>class="active"<%end%>>
        <%=link_to "<i class='fa fa-video-camera fa-2x'></i><label>Monitoreo</label>".html_safe, :root, class: 'item widthlinav topmenulineheight visible-for-medium-up'%>
        <%=link_to "<i class='fa fa-video-camera fa-2x'></i> Monitoreo".html_safe, :root, class: 'visible-for-small-only'%>
        
      </li>
      
      <li class="has-dropdown <% if params[:controller] == 'entries' %>active<%end%>">
        <a class="item widthlinav topmenulineheight visible-for-medium-up"><i class="fa fa-list fa-2x"></i> <label>Lista</label></a>
        <a class="visible-for-small-only"><i class="fa fa-list fa-2x"></i> Lista</a>
        <ul class="dropdown">
          <li><%=link_to "Todo", entries_path(format: :html)%></li>
          <li><%=link_to "Placas Corregidas", entries_edited_path(format: :html)%></li>
        </ul>
      </li>

      <li <% if params[:controller] == 'matchings' %>class="active"<%end%>>
        <%=link_to "<i class='fa fa-link fa-2x'></i><label>Aparear</label>".html_safe, matchings_path(format: :html), class: 'item widthlinav topmenulineheight visible-for-medium-up'%>
        <%=link_to "<i class='fa fa-link fa-2x'></i> Aparear".html_safe, matchings_path(format: :html), class: 'visible-for-small-only'%>
      </li>

      <li class="has-dropdown <% if params[:controller] == 'white_lists' %>active<%end%>">
        <a class="item widthlinav topmenulineheight visible-for-medium-up"><i class="fa fa-star fa-2x"></i> <label style="width: 78px">Lista Blanca</label></a>
        <a class="visible-for-small-only"><i class="fa fa-star fa-2x"></i> Lista Blanca</a>
        <ul class="dropdown">
          <li><%=link_to "Todo", white_lists_path(format: :html)%></li>
          <li><%=link_to "Detectadas", white_lists_detected_path(format: :html)%></li>
        </ul>
      </li>

      <li class="has-dropdown <% if params[:controller] == 'black_lists' %>active<%end%>">
        <a class="item widthlinav topmenulineheight visible-for-medium-up"><i class="fa fa-exclamation-triangle fa-2x"></i> <label>Lista Negra</label></a>
        <a class="visible-for-small-only"><i class="fa fa-exclamation-triangle fa-2x"></i> Lista Negra</a>
        <ul class="dropdown">
          <li><%=link_to "Todo", black_lists_path(format: :html)%></li>
          <li><%=link_to "Detectadas", black_lists_detected_path(format: :html)%></li>
        </ul>
      </li>
      
      <% if current_user.role == "admin" %>
      <li class="has-dropdown <% if params[:controller] == 'settings' || params[:controller] == 'users' %> active<%end%>" >
        <a class="item widthlinav topmenulineheight visible-for-medium-up"><i class="fa fa-gear fa-2x"></i><label>Configuración</label></a>
        <a class="visible-for-small-only"><i class="fa fa-gear fa-2x"></i> Configuración</a>
        <ul class="dropdown">
          <li><%= link_to "Configuración", settings_path(format: :html) %></li>
          <li><%= link_to "Usuarios", users_path %></li>
        </ul>
      </li>
      <% end %>

  </section>
</nav>
<% end %>