config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  root to: 'site#index'
  resources :entries, only: [:index, :create, :update], defaults: {format: 'json'}
  resources :messages, only: [:index]
  resources :main
  resources :matchings
  resources :settings, only:[:index, :show, :create, :update]
  resources :black_lists, except: [:show, :destroy]
  resources :white_lists, except: [:show]
  resources :cameras
  resources :parking_cameras, only:[:index, :update, :show, :destroy]
  resources :brands, only:[:show]

  put 'parking_cameras' => 'parking_cameras#update'
  post 'parking_cameras' => 'parking_cameras#create'
  post 'site/create_manual' => 'site#create_manual'
  get 'brands/all_brands' => 'brands#all_brands'
  post 'conf_manager' => 'settings#conf_manager'
  get 'get_conf_manager' => 'settings#get_conf_manager'
  post 'settings/path' => 'settings#path'
  get 'path_result' => 'settings#path_result'
  get 'drop_tables' => 'settings#drop_tables'
  post 'backup_usb' => 'settings#backup_usb'
  get 'reboot_system' => 'settings#reboot_system'

  get  'entries/search' => 'entries#search', as: 'entries_search'
  get  'entries/edited' => 'entries#edited', as: 'entries_edited'
  get  'black_lists/detected' => 'black_lists#detected', as: 'black_lists_detected'
  post 'black_lists/destroy'  => 'black_lists#destroy',  as: 'black_lists_destroy'
  get  'white_lists/detected' => 'white_lists#detected', as: 'white_lists_detected'
  post 'white_lists/search_b' => 'white_lists#search_b', as: 'white_lists_search_b'
  get  'white_lists/search'   => 'white_lists#search',   as: 'white_lists_search'
  post 'white_lists/destroy'  => 'white_lists#destroy',  as: 'white_lists_destroy'
  post 'white_lists/update'   => 'white_lists#update',   as: 'white_lists_update'
  post 'black_lists/search_w' => 'black_lists#search_w', as: 'black_lists_search_w'
  post 'settings/url_config'  => 'settings#url_config',  as: 'config_urls'
  post 'cameras/create' => 'cameras#create'

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @parking_setting = ParkingSetting.first
    @parking_cameras_in = ParkingCamera.where(type_of: 'Entrada', state: true)
    @parking_cameras_out = ParkingCamera.where(type_of: 'Salida', state: true)
  	
    @entry = Entry.new
    @entries = Entry.where(edit: true, edited: nil)
  	
    @entry_type_1 = Entry.where(entry_type: 1)[0]
  	@entry_type_2 = Entry.where(entry_type: 2)[0]

    if !@entry_type_1.nil?
    	if WhiteList.where('plate = ?', @entry_type_1.plate_chars.to_s).count('id') > 0
    		@state_input = "Acceso permitido."
    	else
    		@state_input = "Acceso denegado."
    	end
    end
    if !@entry_type_2.nil?
      if WhiteList.where('plate = ?', @entry_type_2.plate_chars.to_s).count('id') > 0
        @state_output = "Acceso permitido."
      else
        @state_output = "Acceso denegado."
      end
    end
  	#@entry_type_1 = nil
  	#@entry_type_2 = nil
  end

  def create_manual
    require 'open-uri'
    entry = Entry.new(manual_params)
    entry.creation_date_at_device = Time.now
    entry.plate_segment_url = ""
    time = Time.now.to_s
    entry.full_image_url = Rails.root.join('/photos/manual_entry_'+time+'.jpg')
    if entry.entry_type == 1
    	file = open($URL_CAPTURE_INPUT).read
    end
    if entry.entry_type == 2
	    file = open($URL_CAPTURE_OUTPUT).read
    end
    #file.force_encoding("utf-8")
    File.write('/home/odroid/Documents/ebzer-web/public/photos/manual_entry_'+time+'.jpg', file)
    respond_to do |format|
      if entry.save
        if entry.entry_type == 1 || entry.entry_type == 2
          if BlackList.where(plate: entry.plate_chars).count('id') > 0
            WebsocketRails[:real_broadcast].trigger('black_list', EntrySerializer.new(entry))            
          elsif WhiteList.where(plate: entry.plate_chars).count('id') > 0
            WebsocketRails[:real_broadcast].trigger('white_list', EntrySerializer.new(entry))
          else
            WebsocketRails[:real_broadcast].trigger('other_entries', EntrySerializer.new(entry))
          end

	  if entry.entry_type == 1
	          %x['/home/odroid/Documents/199']
          end
          if entry.entry_type == 2
        	  %x['/home/odroid/Documents/200']
          end
        end
      end
      format.json{render json: entry, status: :ok}
    end #end repond
  end #Create manual

  private
  def manual_params
    params.require(:entry).permit(:id, :device_id, :full_image_url, :plate_chars, :entry_type, :plate_segment_url, :creation_date_at_device, :image)
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/_white_list.html.erb
<div id="white_list_plate" class="reveal-modal medium" data-reveal aria-labelledby="Editar Placa" aria-hidden="true" role="dialog">
	<h2>Placa en Lista Blanca</h2>
  <div class="small-12 large-5 columns">
  	<img id="white_list_plate_segment_url" src="">
  </div>
  <div class="small-12 large-6 columns" id="white_list_plate_chars">
    <h2></h2>
  </div>
  <div class="small-12 large-6 columns" id="white_list_motivo">
    <h2></h2>
  </div>
  <a class="close-reveal-modal" aria-label="Close" id="close_white_list_plate">&#215;</a>
</div>

app/views/site/index.html.erb
<%content_for :javascript do%>
	<%=javascript_include_tag "site"%>
<%end%>

<br>
<br>
<br>
<div class="row" style="display: none;">
	<div class="small-12 columns">
		<label>Vistas:
			<input id="rack" type="button"  value="Rejilla">
			<input id="double_vision" type="button"  value="Doble">
		</label>
	</div>
</div>

<div class="row" id="view_default">
	<% flash.each do |key, value| %>
		<div data-alert class="alert-box success radius">
	  		<%= value %>
	  		<a href="#" class="close">&times;</a>
		</div>    	
	<% end %>
  
  	<!-- Entrada -->
  	<div class="small-12 large-6 columns">
	  	<h2>Entrada</h2>
	  	<div class="row">
	  		<div class="small-4 columns">
	  			<select id="select_in">
	  				<%@parking_cameras_in.each do |pc|%>
	  					<option value="<%=pc.id%>">
	  					<%=pc.description %>
	  					</option>
	  				<% end %>
	  			</select>
	  		</div>
	  		<div class="small-8 columns"></div>
	  	</div>
	  	<ul class="clearing-thumbs" data-clearing>
	      	<li>
	      		<embed id="embed_in" type="application/x-vlc-plugin" pluginspage="http://www.videolan.org"
				version="VideoLAN.VLCPlugin.2" autoplay="yes" loop="no" width="460" height="316" target="" controls="off" style="border: 5px solid green" />
			</li>
		</ul>
		<br>
  </div>
  <!--Fin Entrada -->
  
  <!-- Salida -->
  	<div class="small-12 large-6 columns">
		<h2>Salida</h2>
		<div class="row">
	  		<div class="small-4 columns">
	  			<select id="select_out">
	  				<%@parking_cameras_out.each do |pc|%>
	  					<option value="<%=pc.id%>">
	  					<%=pc.description %>
	  					</option>
	  				<% end %>
	  			</select>
	  		</div>
	  		<div class="small-8 columns"></div>
	  	</div>
		<ul class="clearing-thumbs" data-clearing>
			<li>
		   		<embed id="embed_out" type="application/x-vlc-plugin" autoplay="yes" loop="no" width="460" height="316" target="" controls="off" style="border: 5px solid red"/>
			</li>    
		</ul>
		<br>
  	</div>
	<!-- Fin Salida-->
</div>

<div id="rack_vision" style="display: none">

</div>

<div class="row">
<!--Entrada Manual -->
<!-- rtsp://DBT:1977@192.168.1.60:554 -->
	<div class="large-6 columns">
		<div class="small-6  columns " style="padding-left: 0;">
			<% if @entry_type_1 != nil %>
	                <% if @entry_type_1.plate_segment_url == "" %>
	                        <ul class="clearing-thumbs" data-clearing>
		                		<li>
		                			<a id="entry_full_image_link"  href="http://<%=@entry_type_1.full_image_url%>">
		                    			<strong>Entrada Manual</strong><br><br>
		                			</a>
		                		</li>
	                		</ul>
	                <% else %>
		                <ul class="clearing-thumbs" data-clearing>
			                <li>
			                	<a id="entry_full_image_link"  href="http://<%=@entry_type_1.full_image_url%>">
				                    <img id="entry_plate_segment" 
				                         src="http://<%= @entry_type_1.plate_segment_url %>" alt="" 
				                         style="border: 3px solid blue; height: 75px; width: 142px;">
								    <br>
								    <br>
			                	</a>
			                </li>
		                </ul>
	                <% end %>
			<% end %>
	    </div>

		<div class="small-6 columns" style="padding: 0;">
			<p><strong>Placa: <span id="entry_plate"><%=@entry_type_1.nil? ? '' : @entry_type_1.plate_chars%></span></strong></p>
			<p><strong>Fecha: <span id="entry_date"><%=@entry_type_1.nil? ? '' : @entry_type_1.date%></span></strong></p>
		</div>
		
		<div class="small-6  clearb">
			<p><strong>Hora: <span id="entry_hour"><%=@entry_type_1.nil? ? '' : @entry_type_1.hours%></span></strong></p>
			<p><strong>Estado: <span id="estado_entrada"><%=@entry_type_1.nil? ? '' : @state_input %></span></strong></p>
			<p><a href="#" class="button" data-reveal-id="entrada_manual" id="entrada_manual_button">Entrada Manual</a></p>
		</div>

	</div>

	<!--Salida Manual -->
	<div class="large-6 columns">
		<div class="small-6 columns " style="padding-left: 0;">
		<% if @entry_type_2 != nil %>
			<% if @entry_type_2.plate_segment_url == "" %>
				<ul class="clearing-thumbs" data-clearing>
					<li>
						<a id="exit_full_image_link"  href="http://<%=@entry_type_2.full_image_url%>">
					    	<strong>Salida Manual</strong>
					    	<br>
					    	<br>
						</a>
					</li>
				</ul>
			<% else %>
				<ul class="clearing-thumbs" data-clearing>
	                <li>
	                	<a id="exit_full_image_link"  href="http://<%=@entry_type_2.full_image_url%>">
		                	<img id="exit_plate_segment" src="http://<%= @entry_type_2.plate_segment_url %>" alt="" 
						 	style="border: 3px solid blue; height: 75px; width: 142px;">
						    <br>
						    <br>
						</a>
					</li>
                </ul>
			<% end %>
		<% end %>
	</div>

  	<div class="small-6  columns left" style="padding: 0;">
		<p><strong>Placa: <span id="exit_plate"><%=@entry_type_2.nil? ? '' : @entry_type_2.plate_chars%></span></strong></p>
		<p><strong>Fecha: <span id="exit_date"><%=@entry_type_2.nil? ? '' : @entry_type_2.date%></span></strong></p>
  	</div>

  	<div class="small-6  clearb">
		<p><strong>Hora: <span id="exit_hour"><%=@entry_type_2.nil? ? '' : @entry_type_2.hours%></span></strong></p>
		<p><strong>Estado: <span id="estado_salida"><%=@entry_type_2.nil? ? '' : @state_output %></span></strong></p>
		<p><a href="#" class="button" data-reveal-id="salida_manual" id="salida_manual_button">Salida Manual</a></p>  		
  	</div>
  	</div>
</div>

<div id="entrada_manual" class="reveal-modal medium" data-reveal aria-labelledby="Entrada Manual" aria-hidden="true" role="dialog">
  	<%=form_for @entry, url: site_create_manual_path, format: :json, remote: true, method: :post, html: {id: 'entry_manual', class: 'entry_manual'} do |f|%>
		<h2>Entrada Manual</h2>
		<h3>Placa: </h3> 
		<p id="entrada_mensaje"></p>
		<div class="small-6 columns">
			<input type="text" name="entry[plate_chars]" id="entrada_manual_plate">
		</div>
		<div class="small-6 columns">
			<input type="hidden" name="entry[full_image_url]" value="">
			<input type="hidden" name="entry[device_id]" value="1">
			<input type="hidden" name="entry[entry_type]" value="1">
			<input type="submit" class="button small" value="Guardar" id="entrada_submit">
			<img src="/assets/ajax-loader.gif" width="32px" height="32px" alt="Por favor, espere..." id="entrada_gif" >
		</div>
	<% end %>
  <a class="close-reveal-modal" aria-label="Cerrar" id="close_entrada_manual">&#215;</a>
</div>

<div id="salida_manual" class="reveal-modal medium" data-reveal aria-labelledby="Salida Manual" aria-hidden="true" role="dialog">
  	<%=form_for @entry, url: site_create_manual_path, format: :json, remote: true, method: :post, html: {id: 'entry_manual', class: 'entry_manual'} do |f|%>
		<h2>Salida Manual</h2>
		<h3>Placa: </h3> 
		<p id="salida_mensaje"></p>
		<div class="small-6 columns">
			<input type="text" name="entry[plate_chars]" id="salida_manual_plate">
		</div>
		<div class="small-6 columns">
			<input type="hidden" name="entry[full_image_url]" value="">
			<input type="hidden" name="entry[device_id]" value="2">
			<input type="hidden" name="entry[entry_type]" value="2">
		   	<input type="submit" class="button small" value="Guardar" id="salida_submit">
			<img src="/assets/ajax-loader.gif" width="32px" height="32px" alt="Por favor, espere..." id="salida_gif" >
		</div>
	<%end%>
  <a class="close-reveal-modal" aria-label="Cerrar" id="close_salida_manual">&#215;</a>
</div>

<div id="black_list_plate" class="reveal-modal medium" data-reveal aria-labelledby="Editar Placa" aria-hidden="true" role="dialog">
	<h2>Placa en Lista Negra</h2>
  <div class="small-12 large-5 columns">
  	<img id="black_list_plate_segment_url" src="">
  </div>
  <div class="small-12 large-6 columns" id="black_list_plate_chars">
    <h2></h2>
  </div>
  <div class="small-12 large-6 columns" id="black_list_motivo">
    <h2></h2>
  </div>
  <a class="close-reveal-modal" aria-label="Close" id="close_black_list_plate">&#215;</a>
</div>

<%= render 'white_list' %>

<div id="confirmacion" class="reveal-modal tiny" data-reveal aria-labelledby="secondModalTitle" aria-hidden="true" role="dialog">
  <p>Esta seguro de continuar con la operación?</p>
  <a class="button" id="continue">Continuar</a>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>